<?php

return [

    /*
    |--------------------------------------------------------------------------
    | License Server URL
    |--------------------------------------------------------------------------
    | The URL of your personal license validation server.
    | In development this is https://licensing.test/
    | In production, set LICENSE_SERVER_URL to your public IP or tunnel URL.
    */
    'server_url' => env('LICENSE_SERVER_URL', 'https://licensing.test'),

    /*
    |--------------------------------------------------------------------------
    | Activation Endpoint
    |--------------------------------------------------------------------------
    */
    'activate_endpoint' => env('LICENSE_ACTIVATE_ENDPOINT', '/api/activate'),

    /*
    |--------------------------------------------------------------------------
    | License File Path
    |--------------------------------------------------------------------------
    | Where the signed .lic blob is stored on the client's server.
    */
    'file_path' => storage_path('license/license.lic'),

    /*
    |--------------------------------------------------------------------------
    | RSA Public Key
    |--------------------------------------------------------------------------
    | The RSA-2048 public key used to verify license file signatures.
    | This key was generated by running: php artisan license:generate-keys
    | on the licensing server at C:/Users/<account>/Herd/licensing
    |
    | To override (e.g. after regenerating keys), set HRIS_LICENSE_PUBLIC_KEY
    | in .env as a base64-encoded PEM:
    |   HRIS_LICENSE_PUBLIC_KEY="$(base64 -w0 storage/app/license_public.pem)"
    */
    'public_key' => env('HRIS_LICENSE_PUBLIC_KEY')
        ? base64_decode(env('HRIS_LICENSE_PUBLIC_KEY'))
        : <<<'PEM'
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsj5dXr5TLlE/xlXrtYXu
D0TDrDmHKnfB9ltunYLyM0UHYmirC3AHE3WBieCYDcSQoKXXVSC4erKBScDYsR29
3DVzpxm4HTTlo1OBJuLteo2rSDKKY+VHLz2r9MpwT0T3dYX1AxAK6R3Vd0j0SJ/N
9EmUOlaf/n8HLFSXoUNCs4cmFI2FM1qqKiLcBnvMPZGoANWlmeAsN+1QAtxxhVMU
tSy1C+qfG8EJMSUU7CoDklQz0eEzdPiLb1ZZBkyGI6C4Hxe8MuV1vLctX4v8rHrb
ZIvQ6usrxyWSeZ9wuf2R3rkc1ejXJoO+K8EVeWSJrvYJf9NSRa9FuFzRqiUfI0zM
QQIDAQAB
-----END PUBLIC KEY-----
PEM,

    /*
    |--------------------------------------------------------------------------
    | Enforce License Check in Tests
    |--------------------------------------------------------------------------
    | Set to true in specific tests that need to exercise the middleware.
    | All other tests bypass the license check automatically.
    */
    'enforce_in_tests' => false,

];
